import Head from "next/head";
import { useRouter } from "next/router";

export default function ErrorPage() {
  const router = useRouter();
  const { error } = router.query;

  return (
    <>
      <Head>
        <title>Error</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen w-full flex-col items-center justify-center bg-gray-800 text-white">
        <div className="max-w-lg p-8 text-center">
          <div className="mb-4 text-6xl">
            <span role="img" aria-label="warning">
              ⚠️
            </span>
          </div>

          <h1 className="mb-4 text-3xl font-semibold">
            Ooops! Terjadi masalah saat Sign-in
          </h1>

          <p className="mb-6 text-lg">
            Kami tidak dapat memverifikasi akun Anda. Silakan coba lagi
          </p>

          {error && (
            <p className="mb-6 text-sm text-gray-400">
              <strong>Detail Error:</strong> {error}
            </p>
          )}

          <div>
            <button
              onClick={() => router.push("/auth/sign-in")}
              className="rounded-lg bg-blue-500 px-8 py-6 text-white transition duration-200 hover:bg-blue-700"
            >
              Kembali ke Halaman sign-in
            </button>
          </div>
        </div>
      </main>
    </>
  );
}
